### ISSUE TITLE
触摸板有驱动吗

### ISSUE THREAD

**Issue by zhangyugehu** [ic005k/DELL7472#1]
用了你的EFI

除了无线和触摸板都完美

无线打算换网卡

所以触摸板有驱动吗

**Comment by ic005k** [comment]
里面有触控板的驱动，就是voodooi2c那两个kext，是可以正常工作的。
如果你是新安装或新升级的系统，必须要重建缓存，触控板才能正常工作，建议重建缓存之后再重启系统看看，触控板应该就能正常了。

**Comment by zhangyugehu** [comment]
> 里面有触控板的驱动，就是voodooi2c那两个kext，是可以正常工作的。
> 如果你是新安装或新升级的系统，必须要重建缓存，触控板才能正常工作，建议重建缓存之后再重启系统看看，触控板应该就能正常了。
好的
