### ISSUE TITLE
imessage激活求指导

### ISSUE THREAD

**Issue by zzp1024** [ic005k/DELL7472#19]
![image](https://user-images.githubusercontent.com/2190828/99220408-968c4280-2819-11eb-96b1-9f00d567e072.png)

一直提示失败
问了官方客服说是账号没有问题
我试过换三码的教程  还是不行

**Comment by ic005k** [comment]
这个目前好像没有完美且长久的解决办法，我的办法是：使用自己白果设备（比如iPad、iPhone等）上登录的账号在黑果上登录iMessage就可以长久使用了。不过这玩意儿在国内也没什么人用，个人觉着没必要折腾这个。

**Comment by ic005k** [comment]
还有国内的远景论坛可能会有更过的人讨论这些问题，建议你去看看。
