### ISSUE TITLE
BCM94360CS2 Cause Preference Error and Lag

### ISSUE THREAD

**Issue by petrukngantuk** [ic005k/DELL7472#2]
I bought BCM94360CS2 with Converter and Replace the Wireless card in Dell 7472...
BCM94360CS2 Cause Preference Error and Lag, something when booting, and the Wifi Indicator on off randomly for no reason...
I'm Using Mojave

Is there a way to fix this?

**Comment by ic005k** [comment]
There may be a problem during the hardware installation. Please check if there is any insulation between the riser card and the motherboard.
I wish you all the best!
