### ISSUE TITLE
个人小建议

### ISSUE THREAD

**Issue by zzp1024** [ic005k/DELL7472#21]
README.md更新一下~现在BIOS已经更新了，删除一些老旧的注意事项

更新OC文件的时候备注下建议的OpenCore Configurator或者QtOpenCoreConfig版本，
最近一个星期已经更新了3个tags 不知道是哪个oc版本了

观看历史记录都是更新的开发版，个人建议出0.6.4正式版的时候 出个oc的包

最后万分感谢你带给我们的完美的EFI

谢谢，再次感觉

**Comment by ic005k** [comment]
好的，感谢反馈！
