### ISSUE TITLE
How to solve 1820A with OC

### ISSUE THREAD

**Issue by Staby2000** [ic005k/DELL7472#3]
How to solve 1820A with OC?
It work on the clover , but it seems not working on the OC
I have put all the drivers in the fold, and edited the config.plist

Help!

**Comment by rizalgunawan** [comment]
Is this issue resolved?
I have the same problem

**Comment by Staby2000** [comment]
Not yet.. 
Still using Clover

**Comment by rizalgunawan** [comment]
Hai @Staby2000, can you share your efi / clover config to me?

**Comment by rizalgunawan** [comment]
https://prnt.sc/qcfida

Finally I was able to make it work on Catalina and Mojave with [pin-masking](http://7.daliansky.net/DW1820A/DW1820A_Cover_pins.jpg)
as describe in daliansky blog's [this](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html), in Catalina it works without kext, but BT and AirDrop doesn't work.

In Mojave it works with AirportBrcmFixup.kext installed in L/E

My Card part number is CN-096JNT, 1028:0022
