### ISSUE TITLE
reset nvram怎么没

### ISSUE THREAD

**Issue by zzp1024** [ic005k/DELL7472#33]
![image](https://user-images.githubusercontent.com/2190828/110081477-f4439b00-7dc6-11eb-94e3-182335322661.png)

Ubuntu哪来的？  不是应该是reset nvram吗？

**Comment by ic005k** [comment]
这个我倒没注意，我很久没用这个功能了，你按照下面的设置，看看能否有复位按钮出现。
Ubuntu是我这边引导Linux使用的，你那边不用的话，可以删掉的。
![Uploading resetnvram.png…]()
