### ISSUE TITLE
Combojack helper

### ISSUE THREAD

**Issue by BrandowBuenos** [ic005k/DELL7472#53]
Hi guys, I have a Dell 7472 with macOS big sur and I've always used combojack to solve the headset problem. However, it's been a while since I've been able to use the headset anymore. I do the entire installation, but I can no longer take the snapshot using ProperTree. After the snapshot, the boot does not take place. Any way to solve?

**Comment by ic005k** [comment]
Please use a separate sound card driver for the 7472, please delete all previous files around the sound card driver and use this file again, please note: only this one ALC256.ke x t file is needed.

https://github.com/ic005k/ALC256

**Comment by ic005k** [comment]
You can refer to this EFI below, good luck.

https://github.com/ic005k/DELL7472/releases/tag/20211112

**Comment by BrandowBuenos** [comment]
Thanks for helping @ic005k :D
