### ISSUE TITLE
关于触控板点击的小问题

### ISSUE THREAD

**Issue by LaplaceSoda** [ic005k/DELL7472#56]
触控板操作指令可以实现单指滑动、触控板按下、双指滑动等功能，但经过测试无法实现单指点击(非按下)的操作，即无法实现单指点击选择、单指点击取消选择等操作。

**Comment by ic005k** [comment]
需要在触控板的设置里面选择“轻点来点按“，你检查设置看看是否选中了这个。

**Comment by LaplaceSoda** [comment]
好的，我回头试一下

**Comment by ISPP2056** [comment]
大佬好，dell7472也装了个12.2 今天更到了12.3但一直有休眠后键盘失效的问题，不知道哪里不对

**Comment by ic005k** [comment]
> 有休眠后键盘失效的问题

你直接用我最新发布的EFI测试看看？
https://github.com/ic005k/DELL7472/releases/tag/20220127

**Comment by ISPP2056** [comment]
> 

> > 有休眠后键盘失效的问题
> 你直接用我最新发布的EFI测试看看？ https://github.com/ic005k/DELL7472/releases/tag/20220127
刚试了还是清了Nvram的，进不去系统。

**Comment by zzp1024** [comment]
> > 
> 
> > > 有休眠后键盘失效的问题
> > > 你直接用我最新发布的EFI测试看看？ https://github.com/ic005k/DELL7472/releases/tag/20220127
> > > 刚试了还是清了Nvram的，进不去系统。

进系统肯定没有什么问题。。。。我用的就是最新的 没有问题 你有外接显示器嘛？？帮忙测试一下HDMI能用不？？？？

**Comment by ISPP2056** [comment]
> > > 
> > 
> > 
> > > > 有休眠后键盘失效的问题
> > > > 你直接用我最新发布的EFI测试看看？ https://github.com/ic005k/DELL7472/releases/tag/20220127
> > > > 刚试了还是清了Nvram的，进不去系统。
> 
> 进系统肯定没有什么问题。。。。我用的就是最新的 没有问题 你有外接显示器嘛？？帮忙测试一下HDMI能用不？？？？

就是说奇怪阿，按理是没问题的，我就是用你原来的EFI装的机
