### ISSUE TITLE
macOS Ventura 已发布

### ISSUE THREAD

**Issue by zzp1024** [ic005k/DELL7472#60]
有谁升级成功的嘛？？？听说要先更新OC到0.8.0？？？

**Comment by ic005k** [comment]
这个我可能暂时不急于升级了，刚开始问题可能比较多
关注中

**Comment by sohne-ck** [comment]
怎么样也得等到beta7或着8比较稳定的了吧

**Comment by ic005k** [comment]
> 怎么样也得等到beta7或着8比较稳定的了吧

我今天试了下，正常安装基本没问题，就是会无规律地死机（说不准什么时候鼠标就不动活了），目前正常查找原因中

**Comment by ic005k** [comment]
macOS13感觉还真不错，似乎非常轻量。感觉十分流畅和轻快，已打算日常使用，不再退回12了

**Comment by sohne-ck** [comment]
老生常谈--这次的HDMI能用吗哈哈哈哈

**Comment by ic005k** [comment]
> 关机能断电吗？

我这边貌似不能，只是黑屏，不能断电，原因暂时不明

**Comment by ic005k** [comment]
> 老生常谈--这次的HDMI能用吗

目前手头没有HDMI显示设备测试，等其他用户回答
我估计不会很完美，因为我们这个显卡一直在HDMI方面存在一些问题，不能完美地使用HDMI输出

**Comment by ic005k** [comment]
用了两天，目前已知问题如下：
1.不能正常睡眠
2.不能正常重启和关机
其他暂时还没发现有什么问题

**Comment by ic005k** [comment]
目前已完全正常，可下载我最新发布的EFI参考下。

**Comment by zzp1024** [comment]
感谢更新~~我升级一下~~~测试一下HDMI.。。

**Comment by ic005k** [comment]
> 我升级一下~~~测试一下HDMI

好的，到时告知下HDMI的测试结果，看看有没有突破

**Comment by zzp1024** [comment]
我发现一个很悲剧的事情 ~~现在是不是还没有Intel的无线网卡驱动哦    算了我先升级 用有线吧。。。。。

**Comment by zzp1024** [comment]
更新了一下EFI系统崩了。。。。进不去了。。。。。。

**Comment by ic005k** [comment]
> 更新了一下EFI系统崩了。。。。进不去了。。。。。。

先屏蔽掉Intel无线网卡看看，可能跟这些驱动有关系，我用的是苹果原装无线网卡，不存在驱动无线网卡的问题，很正常

**Comment by zzp1024** [comment]
真进不去了~~~[https://i.postimg.cc/BvZ4JRrx/20220611201131.jpg](url)

**Comment by zzp1024** [comment]
难道最新的EFI在Monterey下不能用的？？？？

**Comment by zzp1024** [comment]
卡  【eb|#log:exitbs:start】

**Comment by ic005k** [comment]
> 难道最新的EFI在Monterey下不能用的？

这我就没法测试了，我这边目前只有13了，12冲掉了
你完全用我发的EFI试试？

**Comment by zzp1024** [comment]
> > 难道最新的EFI在Monterey下不能用的？
> 
> 这我就没法测试了，我这边目前只有13了，12冲掉了 你完全用我发的EFI试试？

我就是用你最新的EFI  进不去12了。。。我用1月份的efi能进12升级13吗？？？

**Comment by zzp1024** [comment]
注意：Msr请自行解锁，如果不想解锁，可勾选“AppleXcpmCfgLock”    可能就是因为这个起不来了  这个咋解锁~~

**Comment by ic005k** [comment]
> 这个咋解锁

过程不是一两句能说明白的，你可以搜下相关教程，也不难搞定。
你直接勾选“AppleXcpmCfgLock”，效果一样

**Comment by zzp1024** [comment]
勾选“AppleXcpmCfgLock”后用最新的EFI成功进入12.3   成功更新到13.0beta1 一切都是那么的完美，最后就是差在HDMI上了

HDMI插入和拔出的时候笔记本都会黑屏。一两秒后会亮屏   HDMI没有输出~

**Comment by ic005k** [comment]
> HDMI插入和拔出的时候笔记本都会黑屏。一两秒后会亮屏 HDMI没有输出~

这个就需要你继续研究下了，如果有进展告知一声

**Comment by zzp1024** [comment]
intel无线网卡驱动 Ventura 版本已经发布～～～

**Comment by ic005k** [comment]
> 一两秒后会亮屏 HDMI没有输出

我给你提供另外一个思路，就是将5916改为591B试试看，就是将6改为B

**Comment by zzp1024** [comment]
链接: https://pan.baidu.com/s/1GZXg_TNm6i1EAeQjN6yPtQ?pwd=kqns 提取码: kqns 复制这段内容后打开百度网盘手机App，操作更方便哦


这个EFI提供参考一下~

说实话我真的只会用 不会研究   改不来  
我实验了这个EFI   USB接收器的键盘没有问题    HDMI信号有输出  但是色彩不对 严重偏色 无法使用~~~

**Comment by ic005k** [comment]
好的，我看看。但我没有这样的设备，所以也没法很好地测试它们

**Comment by zzp1024** [comment]
试了一下591B。拔插 黑屏都不出现了～～～～HDMI测试还是挺方便的吧。没有显示器 一般电视都有hdmi口呀

**Comment by ic005k** [comment]
> 试了一下591B。拔插 黑屏都不出现了

这就没法弄了，我目前暂时也没思路了，这也没别的好办法，就是不断地尝试，等我回头找个hdmi显示设备研究下
如果你那边有进展，可随时告知

**Comment by zzp1024** [comment]
测试结束 最新的版本HDMI能用了 输出是1080p   我的显示器是4k30hz的 

有空我试试咋改系统配置文件

**Comment by ic005k** [comment]
好的，后续你再研究下，我是采用一台1080p的电视进行测试的，暂时手头没有现成的4K显示设备，没法对4K显示进行测试和调试

**Comment by zzp1024** [comment]
2K显示器非常正常 HDMI输出

**Comment by ic005k** [comment]
> 2K显示器非常正常 HDMI输出

好，欢迎随时提供测试结果，关于HDMI，你可以继续深入研究下，其实也不存在什么高技术含量，就是调整参数之后来回测试，看看是否正常
我这边相关设备太少，除了笔记本就是手机，也不看电视、不玩游戏，所以没法深入地对HDMI进行测试和研究
