### ISSUE TITLE
IKBC无线键盘不能使用

### ISSUE THREAD

**Issue by zzp1024** [ic005k/DELL7472#61]
发现一个奇怪的小bug。

外接无线键盘 usb接收器的那种   能输入密码进系统。  进系统后 无线键盘 不能使用。重新拔插接收器后问题解决

罗技无线USB接收器的鼠标 无此问题 进系统就能使用～

**Comment by zzp1024** [comment]
之前 12.X系统无此问题的

**Comment by ic005k** [comment]
这个问题不太好界定，我觉着等13走两个测试版本之后再看
或者你看看usb能否再优化一下

**Comment by zzp1024** [comment]
[20220619]无此问题。

后续待观察

**Comment by zzp1024** [comment]
此问题据说在beta8中已经解决 只有ikbc的键盘才有这个问题~~
