### ISSUE TITLE
HDMI睡眠后有输出无显示

### ISSUE THREAD

**Issue by zzp1024** [ic005k/DELL7472#62]
HDMI进系统后有输出 睡眠后外接显示器还在 但是没显示
重新拔插HDMI线后有显示

**Comment by ic005k** [comment]
目前来说，这是一个已知问题，具体原因暂时不可知，等13走几个测试版再观察看看
最简单的方法就是两次睡眠即可解决这个问题，第一次睡眠唤醒是黑屏，再睡一次唤醒就正常了

**Comment by ic005k** [comment]
新版的EFI做了修复，你试下看看：https://github.com/ic005k/DELL7472/releases/tag/20220615

**Comment by zzp1024** [comment]
[20220619]无此问题。
